version: "3"
services:
  pb-api:
    container_name: pb-api
    restart: always
    build: .
    env_file: .env
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      FORCE_COLOR: "true"
    links:
      - pb-db
    depends_on:
      - pb-db
    networks:
      - be-network
  pb-db:
    container_name: pb-db
    image: mongo
    volumes:
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    ports:
      - "$MONGO_PORT:$MONGO_PORT"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - be-network

networks:
  be-network:
    driver: bridge
